#!/bin/bash
virsh start client &> /dev/null
sleep 2
echo 'client启动'
virsh start proxy &> /dev/null
sleep 2
echo 'proxy启动'
virsh start web1 &> /dev/null
sleep 2
echo 'web1启动'
virsh start web2 &> /dev/null
sleep 2
echo 'web2启动'
