#!/bin/bash
i=`cat /root/stulist | wc -l`
let i++
#x=$[RANDOM%$i+1]
#sed -n "${x}p" /root/stulist
n=1
while :
do
if [ $n -eq $i ];then
n=1
fi
clear
sed -n "${n}p" /root/stulist
let n++
sleep 0.1
done 
